version: "3.8"
services:
  frontend:
    image: 905806622013.dkr.ecr.ap-northeast-1.amazonaws.com/zaemonia-docker:latest
    ports:
      - "5000:5000"
    depends_on:
      - web
  app:
    image: zaemonia-docker
    build: ./infra/php
    volumes:
      - ./backend:/work
  web:
    image: nginx:1.18-alpine
    ports:
      - ${WEB_PORT:-443}:443
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/localhost.pem:/etc/nginx/conf.d/localhost.pem
      - ./infra/nginx/localhost-key.pem:/etc/nginx/conf.d/localhost-key.pem
    working_dir: /work
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: