version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${APP_PORT:-8000}:8000
    volumes:
      - ./backend:/work
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME:-zaemonia-database}
      - DB_USERNAME=${DB_USER:-zaemonia}
      - DB_PASSWORD=${DB_PASS:-Masa79308R4Cpf5r}
      - TZ=${TZ:-Asia/Tokyo}
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./backend:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-Asia/Tokyo}
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME:-zaemonia-database}
      - MYSQL_USER=${DB_USER:-zaemonia}
      - MYSQL_PASSWORD=${DB_PASS:-Masa79308R4Cpf5r}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-Masa79308R4Cpf5r}
      - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${DB_PORT:-13306}:3306
volumes:
  db-store: